"""empty message

Revision ID: 3da21529c496
Revises: 2f72312abc13
Create Date: 2021-10-26 20:46:07.786022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da21529c496'
down_revision = '2f72312abc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
